### ISSUE TITLE
IAM Role need one more permission added 

### ISSUE THREAD

**Issue by ntap-dishank** [NetAppDocs/bluexp-azure-netapp-files#24]
### Page URL

https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-set-up-azure-ad.html

### Page title

Set up a Microsoft Entra application

### Summary

Any Azure customer that uses custom IAM/RBAC roles to control create or modify operations related to Azure NetApp files volumes. Since we are letting customer use BXP to deploy and control the volumes we will need to add this below permission as MSFT is now requiring this to manage volumes. 

- Microsoft.Network/virtualNetworks/subnets/read

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
@ntap-dishank, thank you for reaching out. I added this permission to the custom policy in the docs.

Thanks again,
Ben
